"""Generate Game 7's static Swedish recordings with KBLab's NST Piper voice."""

import argparse
import csv
import json
from pathlib import Path
import wave

from piper import PiperVoice


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", required=True, type=Path)
    parser.add_argument("--csv", type=Path, default=Path(__file__).resolve().parents[1] / "words.csv")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent
    output = root / "audio"
    output.mkdir(exist_ok=True)
    voice = PiperVoice.load(str(args.model))
    recordings = {}
    with args.csv.open(encoding="utf-8-sig", newline="") as source:
        for row in csv.DictReader(source):
            if row["Category"].strip() not in {"clothing", "food", "furniture"}:
                continue
            word = row["Swedish"].strip()
            article = row["Article"].strip().lower()
            phrase = word
            if article in {"en", "ett"} and not word.lower().startswith(article + " "):
                phrase = f"{article} {word}"
            if not word or phrase in recordings:
                continue
            filename = row["ID"].strip() + ".wav"
            if Path(filename).name != filename:
                raise ValueError("Vocabulary IDs must be plain filenames")
            with wave.open(str(output / filename), "wb") as wav:
                voice.synthesize_wav(phrase + ".", wav)
            recordings[phrase] = "audio/" + filename
    (root / "pronunciations.js").write_text(
        "// Generated by generate_audio.py; keys are the exact spoken phrases.\n"
        + "window.game07Pronunciations = "
        + json.dumps(recordings, ensure_ascii=False, indent=2, sort_keys=True)
        + ";\n",
        encoding="utf-8",
    )
    print(f"Generated {len(recordings)} Swedish recordings in {output}")


if __name__ == "__main__":
    main()
